"""Output generation for CORE Framework"""

import json
from datetime import datetime
from typing import Dict, Any

from .models import SessionData, PhaseType, QUESTIONS_BY_ID


class OutputGenerator:
    """Generates output in multiple formats from session data"""
    
    def __init__(self, session_data: SessionData):
        self.session_data = session_data
    
    def get_answer(self, question_id: str) -> str:
        """Get answer for a specific question"""
        for answer in self.session_data.answers:
            if answer.question_id == question_id:
                return answer.response
        return ""
    
    def generate_markdown(self) -> str:
        """Generate Markdown project documentation"""
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        session_name = self.session_data.session.name or "Untitled Project"
        
        markdown = f"# {session_name} - CORE Framework Analysis\n\n"
        markdown += f"**Generated**: {timestamp}\n"
        markdown += f"**Session**: {self.session_data.session.id}\n"
        markdown += f"**Framework Version**: {self.session_data.session.version}\n\n"
        
        # Executive Summary
        problem_answer = self.get_answer("C-01")
        success_answer = self.get_answer("C-02")
        
        if problem_answer or success_answer:
            markdown += "## Executive Summary\n\n"
            if problem_answer:
                markdown += f"**Problem**: {problem_answer}\n\n"
            if success_answer:
                markdown += f"**Success Vision**: {success_answer}\n\n"
        
        # Phase sections
        phase_data = {
            "Clarify": ["C-01", "C-02", "C-03", "C-04", "C-05"],
            "Organize": ["O-01", "O-02", "O-03", "O-04", "O-05"],
            "Refine": ["R-01", "R-02", "R-03", "R-04", "R-05"]
        }
        
        question_titles = {
            "C-01": "Problem & Target Users",
            "C-02": "Success Vision (6 months)",
            "C-03": "Unique Value Proposition", 
            "C-04": "Ideal User Experience",
            "C-05": "Scope Boundaries",
            "O-01": "Essential Features (3-5)",
            "O-02": "User Types & Needs",
            "O-03": "Minimum Viable Product",
            "O-04": "Success Metrics",
            "O-05": "Prioritization Framework",
            "R-01": "Technical Risks",
            "R-02": "Resource Constraints",
            "R-03": "Market/Adoption Risks",
            "R-04": "Validation Plan",
            "R-05": "Pivot Triggers"
        }
        
        for phase_name, question_ids in phase_data.items():
            phase_num = list(phase_data.keys()).index(phase_name) + 1
            markdown += f"## Phase {phase_num}: {phase_name}\n\n"
            
            for question_id in question_ids:
                answer = self.get_answer(question_id)
                if answer:
                    markdown += f"### {question_titles[question_id]}\n\n"
                    markdown += f"{answer}\n\n"
        
        # Next Steps
        markdown += "## Next Steps\n\n"
        markdown += "Based on your CORE Framework analysis, consider these implementation priorities:\n\n"
        
        mvp_answer = self.get_answer("O-03")
        features_answer = self.get_answer("O-01")
        risks_answer = self.get_answer("R-01")
        
        if mvp_answer:
            markdown += f"1. **Start with MVP**: {mvp_answer.split('.')[0]}...\n"
        if features_answer:
            markdown += "2. **Focus on Core Features**: Prioritize the essential features you identified\n"
        if risks_answer:
            markdown += "3. **Address Technical Risks**: Plan for the technical challenges you identified\n"
        
        markdown += "4. **Validate Assumptions**: Test your riskiest assumptions before full development\n"
        markdown += "5. **Set Up Metrics**: Implement tracking for your success metrics\n\n"
        
        markdown += "---\n\n"
        markdown += f"*Generated by CORE Framework v{self.session_data.session.version} - Python TUI Implementation*\n"
        
        return markdown
    
    def generate_json(self) -> str:
        """Generate JSON export of session data"""
        return json.dumps(self.session_data.model_dump(), indent=2, default=str)
    
    def generate_ai_prompt(self) -> str:
        """Generate AI implementation prompt"""
        session_name = self.session_data.session.name or "Untitled Project"
        
        prompt = "Based on the following CORE Framework analysis, provide detailed implementation guidance for this project:\n\n"
        
        prompt += "## Project Context\n"
        prompt += f"**Project**: {session_name}\n"
        prompt += f"**Analysis Date**: {datetime.now().strftime('%Y-%m-%d')}\n\n"
        
        # Key insights from each phase
        problem_answer = self.get_answer("C-01")
        value_answer = self.get_answer("C-03")
        features_answer = self.get_answer("O-01")
        mvp_answer = self.get_answer("O-03")
        risks_answer = self.get_answer("R-01")
        
        if problem_answer:
            prompt += f"**Core Problem**: {problem_answer}\n\n"
        if value_answer:
            prompt += f"**Unique Value**: {value_answer}\n\n"
        if features_answer:
            prompt += f"**Essential Features**: {features_answer}\n\n"
        if mvp_answer:
            prompt += f"**MVP Definition**: {mvp_answer}\n\n"
        if risks_answer:
            prompt += f"**Technical Risks**: {risks_answer}\n\n"
        
        prompt += "## Requirements Analysis\n"
        prompt += "Please analyze the complete project requirements based on all 15 questions answered in the CORE Framework:\n\n"
        
        # Include all answers organized by phase
        phase_names = ["Clarify", "Organize", "Refine"]
        phase_questions = [
            ["C-01", "C-02", "C-03", "C-04", "C-05"],
            ["O-01", "O-02", "O-03", "O-04", "O-05"],
            ["R-01", "R-02", "R-03", "R-04", "R-05"]
        ]
        
        for phase_name, questions in zip(phase_names, phase_questions):
            prompt += f"### {phase_name} Phase\n"
            for i, question_id in enumerate(questions, 1):
                answer = self.get_answer(question_id)
                if answer:
                    prompt += f"{i}. {answer}\n"
            prompt += "\n"
        
        prompt += "## Please provide:\n\n"
        prompt += "### 1. Technical Architecture\n"
        prompt += "- Recommended technology stack and frameworks\n"
        prompt += "- System architecture and component breakdown\n"
        prompt += "- Database design and data flow\n"
        prompt += "- Security considerations and implementation\n\n"
        
        prompt += "### 2. Implementation Plan\n"
        prompt += "- Detailed development roadmap with phases\n"
        prompt += "- Sprint planning and milestone definitions\n"
        prompt += "- Resource allocation and timeline estimates\n"
        prompt += "- Risk mitigation strategies\n\n"
        
        prompt += "### 3. Development Guidelines\n"
        prompt += "- Code structure and organization patterns\n"
        prompt += "- Testing strategy and quality assurance\n"
        prompt += "- Deployment and DevOps recommendations\n"
        prompt += "- Performance optimization approaches\n\n"
        
        prompt += "### 4. Success Metrics & Validation\n"
        prompt += "- Key performance indicators (KPIs) to track\n"
        prompt += "- User testing and feedback collection methods\n"
        prompt += "- Analytics implementation recommendations\n"
        prompt += "- Iteration and improvement processes\n\n"
        
        prompt += "Please provide specific, actionable recommendations that directly address the project requirements and constraints identified in the CORE Framework analysis."
        
        return prompt
    
    def generate_all_formats(self) -> str:
        """Generate all formats in a combined output"""
        formats = [
            ("Markdown", self.generate_markdown()),
            ("JSON", self.generate_json()),
            ("AI Prompt", self.generate_ai_prompt())
        ]
        
        combined_output = f"CORE Framework - Complete Documentation Package\n"
        combined_output += f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n"
        combined_output += f"Session: {self.session_data.session.name or 'Untitled Project'}\n\n"
        combined_output += "=" * 60 + "\n\n"
        
        for format_name, content in formats:
            combined_output += f"FILE: {format_name.lower().replace(' ', '_')}.txt\n"
            combined_output += "=" * (len(format_name) + 10) + "\n\n"
            combined_output += content
            combined_output += "\n\n" + "=" * 60 + "\n\n"
        
        return combined_output
