import { SessionData, OutputFormat } from '../types'

export const generateMarkdown = (session: SessionData): string => {
  const { title, answers } = session
  
  return `# ${title}

## Clarify Phase
**Problem**: ${answers.problem || 'Not specified'}
**Target Users**: ${answers.target_users || 'Not specified'}
**Success Metrics**: ${answers.success_metrics || 'Not specified'}
**Scope**: ${answers.scope || 'Not specified'}

## Organize Phase
**Core Features (MVP)**: ${answers.core_features || 'Not specified'}
**Nice-to-Have Features**: ${answers.nice_to_have || 'Not specified'}
**User Journey**: ${answers.user_journey || 'Not specified'}
**Technical Requirements**: ${answers.technical_requirements || 'Not specified'}

## Refine Phase
**Constraints**: ${answers.constraints || 'Not specified'}
**Risks**: ${answers.risks || 'Not specified'}
**Assumptions**: ${answers.assumptions || 'Not specified'}
**Dependencies**: ${answers.dependencies || 'Not specified'}

## Equip Phase
**Timeline**: ${answers.timeline || 'Not specified'}
**Resources**: ${answers.resources || 'Not specified'}
**Next Steps**: ${answers.next_steps || 'Not specified'}

---
*Generated by CORE Framework on ${new Date(session.updatedAt).toLocaleDateString()}*`
}

export const generateJSON = (session: SessionData): string => {
  return JSON.stringify(session, null, 2)
}

export const generateAIPrompt = (session: SessionData): string => {
  const { title, answers } = session
  
  return `You are an expert project manager and technical architect. Based on the following project analysis using the CORE Framework methodology, provide detailed implementation guidance.

PROJECT: ${title}

ANALYSIS:
Problem: ${answers.problem || 'Not specified'}
Target Users: ${answers.target_users || 'Not specified'}
Success Metrics: ${answers.success_metrics || 'Not specified'}
Scope: ${answers.scope || 'Not specified'}
Core Features: ${answers.core_features || 'Not specified'}
User Journey: ${answers.user_journey || 'Not specified'}
Technical Requirements: ${answers.technical_requirements || 'Not specified'}
Constraints: ${answers.constraints || 'Not specified'}
Risks: ${answers.risks || 'Not specified'}
Timeline: ${answers.timeline || 'Not specified'}
Resources: ${answers.resources || 'Not specified'}
Next Steps: ${answers.next_steps || 'Not specified'}

Please provide:
1. Detailed technical architecture recommendations
2. Implementation roadmap with specific milestones
3. Risk mitigation strategies
4. Technology stack recommendations
5. Resource allocation suggestions
6. Success metrics and KPIs to track

Focus on actionable, specific guidance that can be immediately implemented.`
}

export const generateOutputs = (session: SessionData): OutputFormat => ({
  markdown: generateMarkdown(session),
  json: generateJSON(session),
  aiPrompt: generateAIPrompt(session)
})
